# Built-in defaults for ROS 2 3DS Controller
# Override dynamically via touch screen or in SD:/3ds/ros2_3ds_controller/config.ini

domain_id=0
ros_namespace=/nintendo_3ds
camera_topic=/camera/image_raw/compressed
joy_publish_hz=30
joy_deadzone=0.08
peer_ip=
broadcast_ip=
